[package]
name = "code-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prodash = { version = "19.0.1", features = ["render-line", "render-line-crossterm", "signal-hook", "render-line-autoconfigure", "progress-tree"] }
signal-hook = "0.3.14"
image = "0.23.14"
syntect = "4.6.0"
glob = "0.3.0"